Lab_Backend/Lab_Backend/Controllers/OrdersController.cs
using Lab_Backend.Data.Cart;
using Lab_Backend.Data.Services;
using Lab_Backend.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Lab_Backend.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        public OrdersController(IProductService productService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productService.GetByIdAsync(id);

            if (item != null)
                _shoppingCart.AddItemToCart(item);

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetByIdAsync(id);

            if (item != null)
                _shoppingCart.RemoveItemFromCart(item);

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Lab_Backend/Lab_Backend/Controllers/ProductBrandController.cs
using Lab_Backend.Data;
using Lab_Backend.Data.Services;
using Lab_Backend.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_Backend.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductBrandController : Controller
    {
        private readonly IProductBrandService _service;
        private readonly IWebHostEnvironment _he;

        public ProductBrandController(IProductBrandService service, IWebHostEnvironment he)
        {
            _service = service;
            _he = he;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var productBrands = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = productBrands.Where(x => x.Name.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", productBrands);
        }

        //GET: Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST: Create
        public async Task<IActionResult> Create(ProductBrand productBrand, IFormFile logo)
        {
            if (!ModelState.IsValid)
                return View(productBrand);

            if (logo != null)
            {
                //Save image to wwwroot/images
                string fileName = Path.GetFileNameWithoutExtension(logo.FileName);
                string extension = Path.GetExtension(logo.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmddssfff") + extension;
                string path = Path.Combine(_he.WebRootPath + "/Images/", fileName);
                await logo.CopyToAsync(new FileStream(path, FileMode.Create));
                productBrand.Logo = "/Images/" + fileName;
            }
            else
                productBrand.Logo = "/Images/noimage.jpg";

            await _service.AddAsync(productBrand);
            return RedirectToAction(nameof(Index));
        }

        //GET: Edit
        public async Task<IActionResult> Edit(int id)
        {
            var productBrand = await _service.GetByIdAsync(id);

            if (productBrand == null)
                return View("NotFound");

            return View(productBrand);
        }

        //POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductBrand productBrand, IFormFile logo)
        {
            if (!ModelState.IsValid)
                return View(productBrand);

            if (logo != null)
            {
                //Save image to wwwroot/Images
                string fileName = Path.GetFileNameWithoutExtension(logo.FileName);
                string extension = Path.GetExtension(logo.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmddssfff") + extension;
                string path = Path.Combine(_he.WebRootPath + "/Images/", fileName);
                await logo.CopyToAsync(new FileStream(path, FileMode.Create));
                productBrand.Logo = "/Images/" + fileName;
            }
            else
                productBrand.Logo = "/Images/noimage.jpg";

            await _service.UpdateAsync(id, productBrand);
            return RedirectToAction(nameof(Index));
        }

        //GET: Delete
        public async Task<IActionResult> Delete(int id)
        {
            var productBrand = await _service.GetByIdAsync(id);

            if (productBrand == null)
                return View("NotFound");

            return View(productBrand);
        }

        //POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var productBrand = await _service.GetByIdAsync(id);

            if (productBrand == null)
                return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab_Backend/Lab_Backend/Controllers/ProductController.cs
using Lab_Backend.Data;
using Lab_Backend.Data.Services;
using Lab_Backend.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_Backend.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        private readonly IWebHostEnvironment _he;

        public ProductController(IProductService service, IWebHostEnvironment he)
        {
            _service = service;
            _he = he;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var products = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = products.Where(x => x.Name.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", products);
        }

        //GET: Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetDropdownsValues();
            ViewBag.ProductBrands = new SelectList(productDropdownsData.ProductBrands, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST: Create
        public async Task<IActionResult> Create(Product product, IFormFile image)
        {
            if (!ModelState.IsValid)
                return View(product);

            if (image != null)
            {
                //Save image to wwwroot/Images
                string fileName = Path.GetFileNameWithoutExtension(image.FileName);
                string extension = Path.GetExtension(image.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmddssfff") + extension;
                string path = Path.Combine(_he.WebRootPath + "/Images/", fileName);
                await image.CopyToAsync(new FileStream(path, FileMode.Create));
                product.Image = "/Images/" + fileName;
            }
            else
                product.Image = "/Images/noimage.jpg";

            await _service.AddAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //GET: Edit
        public async Task<IActionResult> Edit(int id)
        {
            var productDropdownsData = await _service.GetDropdownsValues();
            ViewBag.ProductBrands = new SelectList(productDropdownsData.ProductBrands, "Id", "Name");

            var product = await _service.GetByIdAsync(id);

            if (product == null)
                return View("NotFound");

            return View(product);
        }

        //POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile image)
        {
            if (!ModelState.IsValid)
                return View(product);

            if (image != null)
            {
                //Save image to wwwroot/images
                string fileName = Path.GetFileNameWithoutExtension(image.FileName);
                string extension = Path.GetExtension(image.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmddssfff") + extension;
                string path = Path.Combine(_he.WebRootPath + "/Images/", fileName);
                await image.CopyToAsync(new FileStream(path, FileMode.Create));
                product.Image = "/Images/" + fileName;
            }
            else
                product.Image = "/Images/noimage.jpg";

            await _service.UpdateAsync(id, product);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        //GET: Details
        public async Task<IActionResult> Details(int id)
        {
            var productDropdownsData = await _service.GetDropdownsValues();
            ViewBag.ProductBrands = new SelectList(productDropdownsData.ProductBrands, "Id", "Name");

            var productDetails = await _service.GetByIdAsync(id);
            return View(productDetails);
        }

        //GET: Delete
        public async Task<IActionResult> Delete(int id)
        {
            var productDropdownsData = await _service.GetDropdownsValues();
            ViewBag.ProductBrands = new SelectList(productDropdownsData.ProductBrands, "Id", "Name");

            var product = await _service.GetByIdAsync(id);

            if (product == null)
                return View("NotFound");

            return View(product);
        }

        //POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var product = await _service.GetByIdAsync(id);

            if (product == null)
                return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab_Backend/Lab_Backend/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1>Not Found</h1>\
        <hr />
        <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home Page</a>
    </div>
</div>

Lab_Backend/Lab_Backend/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Sign in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Sign up
    </a>
}
else
{
    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i>Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Sign out
        </button>
    </form>
}

Lab_Backend/Lab_Backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductBrand" asp-action="Index">Brands</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>